### ISSUE TITLE
After logging in, Gets redirected back to the login page each time.

### ISSUE THREAD

**Issue by ghost** [hymm/squid-tracks#187]
It even skips the login process as the page found out I was logging in again to the same page shortly after. Once I clicked which account I was using, it redirects back to the login page again

**Comment by AdamW19** [comment]
Can confirm. Logging in with the cookie works but logging in via your Nintendo Account doesn't work.

**Comment by Mattlau04** [comment]
I have the exact same issue

**Comment by winnie93123** [comment]
Same problem here

**Comment by yukidaruma** [comment]
It's been 8 months since login stopped working. ([Developer's tweet](https://twitter.com/SquidTracks/status/1045177579466940416))

I recommend you to use https://github.com/frozenpandaman/splatnet2statink to upload to Stat.ink.
Or if you prefer to use SquidTracks anyway (like me), you can just use splatnet2statink for obtaining iksm_session.

I can provide instructions if necessary.
